ログインページとヘッダーバー
nihondanuki/pilotprojectwiki pull request #13
Opened 2018-06-18 09:42 UTC by nihondanuki

# 目的
ユーザーがログインするページを作成、ログイン状況をバーでわかるようにした
# やったこと
ログインページの作成と全ページで使用する_header実装

2018-06-18 09:45 UTC, nihondanuki commented
controllerができてないのでテストが通らないですがcontrollerのプルリクが通ったら変更します

2018-06-18 10:36 UTC, mohsk commented on app/controllers/sessions_controller.rb
> +<<<<<<< Updated upstream
マージミスって変なの残ってますね

2018-06-19 02:29 UTC, nihondanuki commented
修正しました！

2018-06-19 03:21 UTC, nihondanuki commented
修正しました

2018-06-20 05:59 UTC, kiyokuro commented on app/controllers/sessions_controller.rb.orig
> +<<<<<<< HEAD
ここもミスってるから直そう

2018-06-20 05:59 UTC, kiyokuro commented on app/controllers/sessions_controller.rb.orig
> +<<<<<<< HEAD
ここもミスってるから直そう

2018-06-20 06:01 UTC, matsuhisa commented on spec/controllers/users_controller_spec.rb
> +      it
👀 なんだろう...

2018-06-20 06:34 UTC, kazumalab requested changes
コメントしました！
コンフリクト直してもらえるとレビューしやすい！

2018-06-20 06:34 UTC, kazumalab commented on app/controllers/sessions_controller.rb.orig
> +    render 'new'
destroyしたあとはredirect_toしたいです！
renderだとリロードされると毎回destoryが走っちゃうのだったと思います！

2018-06-20 06:34 UTC, kazumalab commented on app/views/layouts/_header.html.haml
> +          = link_to "ログアウト", logout_path, method: :delete
👌

2018-06-20 06:34 UTC, kazumalab commented on app/views/sessions/new.html.haml
> +  = link_to "ログイン", "users/new"
helper使いましょう！

2018-06-20 06:34 UTC, kazumalab commented on spec/controllers/users_controller_spec.rb
> +      it { expect { post :create, params: { user: attributes_for(:user) } }.to change(User, :count).by(1) }
```ruby
change(User, :count)
```

へぇ！知らなかったです！👀

2018-06-20 06:34 UTC, kazumalab commented on spec/controllers/users_controller_spec.rb
> +      it { expect { post :create, params: { user: attributes_for(:user) } }.to change(User, :count).by(1) }
せっかく上で

```
let(:user){build(:user)}
```
を定義しているのであれば、
ここで使ってあげてもいいんじゃないでしょうか？(buildだとハッシュにならないのでattributesにしてあげてみると良さそう)

```ruby
let(:user) { build(:user).attributes }
it { expect { post :create, params: { user: user } }.to change(User, :count).by(1) }
```

2018-06-20 07:33 UTC, matsuhisa commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
XHTML ではないので、 `/` はなくても良さそう

2018-06-20 07:33 UTC, matsuhisa commented on app/views/layouts/mailer.html.haml
> +!!!
メールを送るときがあるんだろうか 🤔 
なければなくても良さそう

2018-06-20 07:33 UTC, matsuhisa commented on app/views/layouts/mailer.text.haml
> += yield
メールを送るときがあるんだろうか 🤔 
なければなくても良さそう

2018-06-20 07:45 UTC, nihondanuki commented on spec/controllers/users_controller_spec.rb
> +      it
消し忘れです！
修正しました！

2018-06-20 08:24 UTC, nihondanuki commented
修正しました！
@matsuhisa @kazumalab @kiyokuro

2018-06-20 08:39 UTC, matsuhisa approved these changes
@nihondanuki 

良さそうなんですけれど

- git のコミットログで、 `a` というのはなんだろう？
- merge じゃなく、git rebase master で次からやりたい
  - わからないときは、お気軽に聞いてくださいね

と、git の操作に関するところが気になりました

2018-06-20 08:43 UTC, kazumalab commented on app/controllers/sessions_controller.rb
> +    redirect_to 'new'
redirect_to new_session_pathとかじゃない？

2018-06-20 09:05 UTC, nihondanuki commented
gitの操作について勘違いしていました　次からはrebaseします
aは修正で適当につけてあとでまとめようとしたのですが技術的に難しかったものです　これもやらないようにします

2018-06-20 09:08 UTC, kiyokuro commented on spec/controllers/users_controller_spec.rb
> +      it { expect { post :create, params: { user: attributes_for(:user) } }.to change(User, :count).by(1) }
```
let(:user) { attributes_for(:user) }
```
残して、上で言われている
```
it { expect { post :create, params: { user: user } }.to change(User, :count).by(1) }
```
にした方が
```
post :create, params: { user: attributes_for(:user) }
```
もuser: userにできて少しスッキリしない？

2018-06-20 09:25 UTC, matsuhisa commented
@nihondanuki 

git で技術的に難しかったのはなんだろう？それとも、操作方法？
もう少し具体的にわかると、次に繋げられそうだと思いました。

というのも、先日に git のことで、1日過ぎてしまったりしたので、同じことが起きない様に解決していきたいからです。

2018-06-20 09:29 UTC, nihondanuki commented
了解しました!少し長くなっちゃうので日報に書きますね！

2018-06-20 09:54 UTC, nihondanuki commented on spec/controllers/users_controller_spec.rb
> +      it { expect { post :create, params: { user: attributes_for(:user) } }.to change(User, :count).by(1) }
なるほどdryにすることを忘れていました
確かにこちらの方がわかりやすそうですね！

2018-06-20 09:56 UTC, kazumalab approved these changes
良さそうです！

2018-06-20 10:03 UTC, merged