ユーザーモデルを作成
nihondanuki/pilotprojectwiki pull request #7
Opened 2018-06-13 06:36 UTC by nihondanuki

ユーザーモデルでは名前とメールアドレスで登録するように設計しました
バリデーションは
name 存在する、50文字まで
email 存在する、50文字まで、文字@文字.文字の正規表現であること、ユニークであること
を要請しました
パスワードについては別のプルリクエストに分けます

2018-06-13 07:34 UTC, kazumalab reviewed
ユーザーpasswordは必要ない？
あとcodecovのやつはignoreしちゃっていいかも。

2018-06-13 07:39 UTC, nihondanuki commented
ちょっとパスワードを入れるとコミットが大きくなりすぎると思ったので次のプルリクに分けました
coverageは次回のプルリクでイグノアしようと思います

2018-06-13 07:49 UTC, kazumalab requested changes
みましたー！

2018-06-13 07:49 UTC, kazumalab commented on app/assets/stylesheets/scaffolds.scss
> +  background-color: #fff;
せっかくscss使うなら色とか変数にしちゃいたい気持ち！
Scaffold使うとそこらへん自動でできちゃうのであれだけども

2018-06-13 07:49 UTC, kazumalab commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validatesはvalidatesで揃えたいから、これ一番上の行に持ってきていいとおもいます！

2018-06-13 07:49 UTC, kazumalab commented on app/views/users/_form.html.haml
> += form_for @user do |f|
rails 5からform_withを使いたい

2018-06-13 07:49 UTC, kazumalab commented on app/views/users/show.json.jbuilder
> +json.partial! "users/user", user: @user
json.jbuilder系使わないから消してもいいかもね！

2018-06-13 07:49 UTC, kazumalab commented on db/schema.rb
> +    t.string "email"
scaffoldで作ったとはいえ、`null: false`ぐらいはつけたいですー！

2018-06-13 07:49 UTC, kazumalab commented on spec/controllers/users_controller_spec.rb
> +      user = User.create! valid_attributes
factory_botを導入したら書き直したいかな！

2018-06-13 07:49 UTC, kazumalab commented on test/system/users_test.rb
> +require "application_system_test_case"
これいらない...

2018-06-13 07:49 UTC, kazumalab commented on spec/views/users/show.html.haml_spec.rb
> +require 'rails_helper'
Viewスペックいらないんじゃない？
消しちゃっていいかも

2018-06-13 07:49 UTC, kazumalab commented on spec/controllers/users_controller_spec.rb
> +    context "with invalid params" do
[nits]時間の許すがぎり、習った方法で、書き直してもいいかも！
このSpecリファクタしまくれるYo!

2018-06-13 08:03 UTC, HamaguchiRyosuke commented on spec/views/users/show.html.haml_spec.rb
> +require 'rails_helper'
Scaffoldで生成される不要なテストやファイルは全部消しちゃって良さそう。それかscaffoldで生成されない設定にしても良さそう。
どっちにするかは任せます！

2018-06-13 08:31 UTC, nihondanuki commented
いらない部分を消してバリデーターを読みやすくしてnull制約もまた追加しました

2018-06-13 08:32 UTC, nihondanuki commented
controllerは別のプルリクエストで書く予定です
factrybot導入
bootstrap導入
ユーザーモデル作成
コントローラー作成
ビュー作成
こんなプルリクにします

2018-06-13 09:59 UTC, nihondanuki commented
shoulda-matcherのuniqueはcreateが必要でした

2018-06-14 02:46 UTC, HamaguchiRyosuke commented
commitがすごいことになってるw

2018-06-14 03:44 UTC, nihondanuki commented
できるだけまとめるようにします😭

2018-06-14 06:38 UTC, merged